# Generated by Django 5.1.2 on 2024-10-17 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_class_customuser_pronouns_customuser_tutoring_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('student', 'Student'), ('ta', 'Teaching Assistant')], default='student', max_length=10),
        ),
    ]
